### ISSUE TITLE
missing `src` directory?

### ISSUE THREAD

**Issue by sbfnk** [jonathonmellor/flu-forecast-2022-23#1]
Hi - we're reading this paper in our journal club. Really interesting!

It seems the `src/` directory and R files in there are missing - could these be added? It would be great to see more details on the modelling approach.

**Comment by jonathonmellor** [comment]
Hi @sbfnk, apologies I didn't get a notification!

Have added the `src/`, it was commit but not pushed - my mistake.

For awareness we don't use this exact same approach any more - the GAM structure is the identical, but we use `gratia::fitted_samples` to generate prediction samples and aggregate at the sample level rather than quantiles, this gives more sensible uncertainty as we aggregate up geographies.

don't think I've ever had a paper read in a journal club before - very cool!
